- front-end/index.html
- front-end/js/main.js
- front-end/js/requestAnimationFramePolyfill.js
- front-end/js/three.js
- front-end/js/typedarrays.js
Added requestAnimationFrame polyfill so that IE doesn't break the app
wants to loop.
Added typed arrays polyfill since Three uses them for the matrices.
Added the links to the polyfills in the html.
Changed so that it sets the renderers pixelRatio to devicePixelRatio or 1 so that it renders in earlier IE's (10 and 9).
> Added polyfills for IE and changes some stuff.

- front-end/css/main.css
- front-end/index.html
- front-end/js/main.js
Adds back the css file and comment out all css.
Comments out the adding of rollOverMesh to scene.
> Added check placement of cube, removing rollOver cube and fix the precision of the mouse click.

- front-end/js/main.js
Changing so pan is not allowed.
Changing so mouseposition be clientX and clientY, fix bug in FF.
Removed unused code.
> Changing so pan is not allowed and so mouseposition be clientX and clientY.

- front-end/js/main.js
Changing X/Y on event to clientX/clientY in onDocumentMouseDown.
> Changing X/Y on event to clientX/clientY in onDocumentMouseDown.

- front-end/js/main.js
> Adding alerts for ios test.

- front-end/js/main.js
> Adding touchevent.

- front-end/js/main.js
> Reset code from ios-test.

- front-end/js/Builder.js
Parameter is now a string value instead
> Removing the need to preappend hexcolor with '0x'

- front-end/js/Builder.js
Added public function toggleBuilMode() in CubeBuilder and public property buildMode in ConstructionArea.
onDocumentMouseTouch(event) checks current buildMode when user clicked on left mousebutton.
Please make check that I haven't violated any privacy rules! :-)
> Remove cube

- front-end/js/Builder.js
No problems found with current code
> Activating setColor()

- front-end/index.html
- front-end/js/Builder.js
> Adding stats counter for easier debugging

- front-end/js/Builder.js
Made positionvalues dependent of baseSize
> Removing hardcoded positions of colorLines

- front-end/js/Builder.js
Test in console:
cb.saveModel() and then copy string and run cb.loadModel(string)
> Adding basic load and save to JSON

- front-end/css/main.css
- front-end/index.html
- front-end/js/Builder.js
- front-end/js/navigation.js
Everything should work fine with the perspectives ui.
> Perspectives ui

- front-end/css/main.css
- front-end/index.html
- front-end/js/Builder.js
- front-end/js/navigation.js
Merged the perspectives-ui branch.
> Solve issue 38

- front-end/css/main.css
- front-end/index.html
- front-end/js/navigation.js
> BaseSize UI created

- front-end/js/Builder.js
Solved #65 by moving the code down so that the public interface is at the
bottom.
> Solve #65.

- front-end/js/Builder.js
Removed the green foundation from builder. This is for the release to client.
> Removed foundation from builder.js

- front-end/js/Builder.js
To keep it DRY I added a method to create ortho cameras. The reason it is
a closure is because the function createPerspectives calculates some
things that are necessary for it to work, and I can't be bothered to solve
it some other way.
Close #40.
> Added createOrthoCamera to createPerspectives

- front-end/js/navigation.js
The problem was that a new click event was set to the same buttons every
time baseContainer modal was opend. This led to that all click event was
activated when changing size (one the first time, two the second time,
and so on...)
> Fixing issue 89.

- public/js/Builder.js
Reverts no222bd/1dv411-Webbprojekt-1#124
> Revert "Fix for issue 96."

- index.html
- public/css/main.css
- public/js/Builder.js
Hides green foundation. See issue #83.
> Issue #122

- public/js/Builder.js
- public/js/navigation.js
Returns if the max/min size has been reached.
> Fixes issue #135

- index.html
- public/js/Builder.js
- public/js/navigation.js
Changing base size options according to wishes from client.
> Changed base size options to 1-10

- public/css/main.css
Works fine on a smaller browser window now but isn't tested on a small
device.
> Fix needs testing on small device

- public/js/navigation.js
As long as nobody creates a control using only divs it should work fine.
Fixes #105.
> Closing modals by pressing background works.

- public/js/navigation.js
Solves #160. This is done by just removing the functions, since they weren't needed.
> Solve issue 160

- public/js/navigation.js
Since the branch was messed up, removed the branch and did it again.
> Moved the renderPerspective call.

- public/js/navigation.js
> Solves issue 138 without messing with everything

- public/js/Builder.js
- public/js/navigation.js
Removed the dependency of colors in the BUILDER by passing them in when initializing ConstructionArea.
> Removed dependency of colors in BUILDER

- public/js/navigation.js
Maybe its better to have it triggered in builder.js instead of navigation.js, but this works for me in chrome.
> Should trigger updateView event when changing size

- public/js/Builder.js
- public/js/navigation.js
BuildMode is now set to Add(true) when user changes color. This is accomplished by using the existing method handleBuildOption().
> Solved Issue #220

- public/css/main.css
Have set border-radius from 40px to 20px when screen-width is less than 960px.
> Issue #213 fix

- public/css/main.css
- public/js/Builder.js
- public/js/navigation.js
- public/test/spec/constructionArea/saveModelSpec.js
- public/test/spec/constructionArea/setCubeMaterialSpec.js
Issue #203. Check if icons bounce.
> Color cube

- public/css/main.css
Added the following line to main.css:
#ThreeJScontainer {
...
...
-webkit-tap-highlight-color:transparent;
}
> Solved issue #236 iOS Flickering

- public/js/navigation.js
Closes modal when clicking on a buildoption.
> Issue #278

- public/css/main.css
Changed size on border-radius on bigger screens but this might have been the wrong screen. Please get back to me with detailed info if this doesn't solve the problem!
> Issue #283
